extends:
  # https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/index.js
  - "@commitlint/config-conventional"

rules:
  body-max-line-length: [1, always, 72]
  footer-max-line-length: [1, always, 72]
  header-max-length: [2, always, 72]
