env:
  browser: true
  es2020: true
  node: true

extends:
  - plugin:jest-dom/recommended
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended
  - plugin:testing-library/react
  - plugin:testing-library/recommended
  - react-app
