branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - release
  - next
  - next-major
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
  - "@semantic-release/commit-analyzer"

  - "@semantic-release/release-notes-generator"

  - - "@semantic-release/changelog"
    - changelogTitle: |-
        # Change Log

        All notable changes to this project are documented in this file. See
        [Conventional Commits](https://conventionalcommits.org) for commit guidelines.

  - - "@semantic-release/npm"
    - pkgRoot: dist

  - "@semantic-release/github"

  - - "@semantic-release/git"
    - message: |-
        chore(release): ${nextRelease.version}

        ${nextRelease.notes}
