name: Deploy GitHub Pages

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up
        run: |
          echo "::set-env name=NODE_VERSION::$(node -v)"
          echo "::set-env name=PNPM_VERSION::$(npx pnpm -v)"

      - name: Cache node packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key:
            node-cache-${{ env.NODE_VERSION }}-${{ env.PNPM_VERSION }}-${{
            hashFiles('./pnpm-lock.yaml') }}
          restore-keys: |
            node-cache-${{ env.NODE_VERSION }}-${{ env.PNPM_VERSION }}-
            node-cache-

      - env:
          CI:
        run: npm run init-dev

      # workflow specific steps

      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
