name: Publish to NPM

on:
  push:
    branches: [release]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up
        run: |
          echo "::set-env name=NODE_VERSION::$(node -v)"
          echo "::set-env name=PNPM_VERSION::$(npx pnpm -v)"

      - name: Cache pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key:
            pnpm-store-${{ env.NODE_VERSION }}-${{ env.PNPM_VERSION }}-${{
            hashFiles('./pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ env.NODE_VERSION }}-${{ env.PNPM_VERSION }}-
            pnpm-store-

      - env:
          CI:
        run: npm run init-dev

      # workflow specific steps

      - run: npm run dist

      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx npm-publish --token=${NPM_TOKEN} ./dist/package.json
