name: test

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - uses: actions/checkout@v2

      - name: Set up
        run: |
          echo "::set-env name=NODE_VERSION::$(node -v)"
          echo "::set-env name=PNPM_VERSION::$(npx pnpm -v)"

      - name: Cache node packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key:
            node-cache-${{ env.NODE_VERSION }}-${{ env.PNPM_VERSION }}-${{
            hashFiles('./pnpm-lock.yaml') }}
          restore-keys: |
            node-cache-${{ env.NODE_VERSION }}-${{ env.PNPM_VERSION }}-
            node-cache-

      - env:
          CI:
        run: npm run init-dev

      # workflow specific steps

      - run: npm run lint

      - env:
          CI: true
        run: npm t
